Create DATABASE ObstaclesCrossed

/*USER*/
CREATE TABLE PLAYER(
ID_USER CHAR(10) PRIMARY KEY,
Nickname  VARCHAR(20),
Email VARCHAR(20),		
Password VARCHAR(20),		
Name VARCHAR(20),		
Sex	CHAR(5),	
Age	INT,
Country	VARCHAR(20),	
Avatar image,		
Coins MONEY,
Character VARCHAR(10),
)
CREATE TABLE SHOP(
ID_CHAR CHAR(10),
Price MONEY,
Status varchar(10),
)
CREATE TABLE PLAYERHISTORY(
Nickname  VARCHAR(20),
ID_USER CHAR(10),
TIME smalldatetime,
)
CREATE TABLE CHARACTER(
ID_CHAR CHAR(10) PRIMARY KEY,
NAME_CHAR VARCHAR(20),	
Photo image,
Explanation VARCHAR(50),
)
ALTER TABLE PLAYERHISTORY
 ADD CONSTRAINT FK_PL_HS
 FOREIGN KEY (ID_USER)
 REFERENCES PLAYER(ID_USER)

ALTER TABLE SHOP
 ADD CONSTRAINT FK_SHOP_CHAR
 FOREIGN KEY (ID_CHAR)
 REFERENCES CHARACTER(ID_CHAR)

